apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w01
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-09-12T07:58:21Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-backend-0
    namespace: monitoring
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: loki-backend
      uid: dcaae880-e759-4148-998a-8c79560bfed3
    resourceVersion: "45498762"
    uid: ace2e6b5-36e4-4714-83b8-0fcbb43767e4
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-ace2e6b5-36e4-4714-83b8-0fcbb43767e4
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w02
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-09-12T07:58:21Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-backend-1
    namespace: monitoring
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: loki-backend
      uid: dcaae880-e759-4148-998a-8c79560bfed3
    resourceVersion: "45498765"
    uid: 998463f1-1be8-4099-88df-b99fd9de0c2e
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-998463f1-1be8-4099-88df-b99fd9de0c2e
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w02
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-08-24T08:55:47Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-write-0
    namespace: monitoring
    resourceVersion: "36359921"
    uid: 59a4b639-96af-4cc1-8d97-7f2e5b597dae
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-59a4b639-96af-4cc1-8d97-7f2e5b597dae
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w01
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-08-24T08:55:47Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-write-1
    namespace: monitoring
    resourceVersion: "36359896"
    uid: 387ff975-16b0-490e-b80f-b8ba2595e3af
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-387ff975-16b0-490e-b80f-b8ba2595e3af
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w03
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-09-07T09:22:23Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: write
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
    name: data-loki-write-2
    namespace: monitoring
    resourceVersion: "43118408"
    uid: d797819a-db1f-4a73-abf6-d7c6bd1d31c8
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-d797819a-db1f-4a73-abf6-d7c6bd1d31c8
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w02
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-08-04T13:11:46Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: zipkin
      app.kubernetes.io/name: cassandra
    name: data-zipkin-cassandra-0
    namespace: monitoring
    resourceVersion: "27931146"
    uid: 6e5103de-8119-4f69-95f6-4020af5b7ceb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-6e5103de-8119-4f69-95f6-4020af5b7ceb
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: prometheus
      meta.helm.sh/release-namespace: monitoring
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w03
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-08-17T12:53:55Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: prometheus
      app.kubernetes.io/version: v3.5.0
      helm.sh/chart: prometheus-27.37.0
    name: prometheus-server
    namespace: monitoring
    resourceVersion: "47911122"
    uid: 40b2db5d-0d23-4a80-b204-9d5b8226d09f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-40b2db5d-0d23-4a80-b204-9d5b8226d09f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: k8s-w01
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-07-09T09:47:05Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: alertmanager
    name: storage-prometheus-alertmanager-0
    namespace: monitoring
    resourceVersion: "20204033"
    uid: 8aa7fdf0-4ce2-479f-865e-a65d7530797c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-8aa7fdf0-4ce2-479f-865e-a65d7530797c
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
